---
  env:
    browser: true
    es6: true

  extends:
    - "eslint:recommended"
    - "plugin:react/recommended"

  #parser: babel-eslint
  parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
      jsx: true
      experimentalObjectRestSpread: true

  plugins:
    - react

  globals:
    module: true
    process: true

  rules:
    no-console: 1
    no-unused-vars: 1
    eqeqeq: 0
    curly: 2
    object-shorthand: 0