database:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
        - ./data/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=u2262s8598_tatar
        - MYSQL_USER=u2262s8598_tatar
        - MYSQL_PASSWORD=password

phpmyadmin:
    image: nazarpc/phpmyadmin
    links:
        - database
    ports:
        - "9999:80"
    environment:
        - MYSQL_HOST=database:3306
        - MYSQL_ROOT_PASSWORD=root


