mysql-db:
    image: mysql
    hostname: mysql-db
    ports:
      - "3306:3306"
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./data/script:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_ROOT_PASSWORD=${DBP_ROOT}
        - MYSQL_DATABASE=${DBP_NAME}
        - MYSQL_USER=${DBP_USER}
        - MYSQL_PASSWORD=${DBP_PASSWORD}

php-myadmin:
    image: nazarpc/phpmyadmin
    links:
        - mysql-db
    ports:
        - "9999:80"
    environment:
        - MYSQL_HOST=mysql-db:3306
        - MYSQL_ROOT_PASSWORD=${DBP_ROOT}


api-server:
    build: .
    dockerfile: /api/Dockerfile
    hostname: api-server
    links:
        - mysql-db
    ports:
        - "9696:80"
    volumes:
        - ./api/application:/var/www/application
        - ./client/public:/var/www/html
        - ./api/etc/php:/usr/local/etc/php
#        - ./api/etc/apache/hosts.conf:/etc/apache2/sites-enabled/000-default.conf
#        - ./api/etc/apache/httpd.conf:/etc/apache2/conf-available/apache2.conf
#        - ./logs/api:/var/www/logs
    environment:
        - ALLOW_OVERRIDE=true
        - DBP_HOST=mysql-db
        - DBP_NAME=${DBP_NAME}
        - DBP_USER=${DBP_USER}
        - DBP_PASSWORD=${DBP_PASSWORD}


web-server:
    build: .
    dockerfile: /client/Dockerfile
    hostname: web-server
    links:
        - api-server
    ports:
        - "9090:80"
        - "9485-9495:9485-9495"
    volumes:
        - ./client/public:/usr/client/public
        - ./client/app:/usr/client/app
        - ./client/package.json:/usr/client/package.json
        - ./client/.eslintrc.yml:/usr/client/.eslintrc.yml
        - ./client/brunch-config.js:/usr/client/brunch-config.js
        - ./client/server.js:/usr/client/server.js
    environment:
        - PROXY_CONTEXT=/api
        - PROXY_TARGET=http://api-server
    command: brunch watch --env proxy --server --port 80


proxy:
    image: haproxy:1.6
    links:
        - web-server
        - api-server
    ports:
      - "9000:80"

    volumes:
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    environment:
        - ALLOW_OVERRIDE=true
        - API_PORT=9696
        - WEB_PORT=9090
