mysql-db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./etc/mysql:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_ROOT_PASSWORD=${DBP_ROOT}
        - MYSQL_DATABASE=${DBP_NAME}
        - MYSQL_USER=${DBP_USER}
        - MYSQL_PASSWORD=${DBP_PASSWORD}

php-myadmin:
    image: nazarpc/phpmyadmin
    links:
        - mysql-db
    ports:
        - "9999:80"
    environment:
        - MYSQL_HOST=mysql-db:3306
        - MYSQL_ROOT_PASSWORD=${DBP_ROOT}


php-server:
    build: .
    dockerfile: /etc/docker/Dockerfile-php-apache
    links:
        - mysql-db
    ports:
        - "8000:80"
        - "8080:8080"
    volumes:
        - ./public:/var/www/html
        - ./application:/var/www/application
#        - ./logs:/var/www/logs
        - ./etc/php:/usr/local/etc/php
#        - ./etc/apache:/etc/apache2/sites-enabled
    environment:
        - ALLOW_OVERRIDE=true
        - DBP_HOST=mysql-db
        - DBP_NAME=${DBP_NAME}
        - DBP_USER=${DBP_USER}
        - DBP_PASSWORD=${DBP_PASSWORD}


brunch:
    build: .
    dockerfile: /etc/docker/Dockerfile-brunch
    volumes:
        - ./public:/usr/public
        - ./client/app:/usr/client/app
        - ./client/package.json:/usr/client/package.json
        - ./client/.eslintrc.yml:/usr/client/.eslintrc.yml
        - ./client/brunch-config.js:/usr/client/brunch-config.js
    environment:
        - ALLOW_OVERRIDE=true
    command: ["/bin/sh", "-c", "npm run watch"]
