mysql-db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./etc/mysql:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_ROOT_PASSWORD=${DBP_ROOT}
        - MYSQL_DATABASE=${DBP_NAME}
        - MYSQL_USER=${DBP_USER}
        - MYSQL_PASSWORD=${DBP_PASSWORD}

php-myadmin:
    image: nazarpc/phpmyadmin
    links:
        - mysql-db
    ports:
        - "9999:80"
    environment:
        - MYSQL_HOST=mysql-db:3306
        - MYSQL_ROOT_PASSWORD=${DBP_ROOT}


php-server:
    build: .
    dockerfile: /etc/docker/Dockerfile-php-apache
    links:
        - mysql-db
    ports:
        - "9000:80"
    volumes:
        - ./client/public:/var/www/html
        - ./application:/var/www/application
#        - ./logs:/var/www/logs
        - ./etc/php:/usr/local/etc/php
#        - ./etc/apache:/etc/apache2/sites-enabled
        - ./etc/apache/httpd.conf:/etc/apache2/conf-enabled/apache2.conf
    environment:
        - ALLOW_OVERRIDE=true
        - APP_PATH=/var/www/application
        - DBP_HOST=mysql-db
        - DBP_NAME=${DBP_NAME}
        - DBP_USER=${DBP_USER}
        - DBP_PASSWORD=${DBP_PASSWORD}


node-brunch:
    build: .
    dockerfile: /etc/docker/Dockerfile-brunch

    ports:
        - "9090:80"
        - "9485-9495:9485-9495"
    volumes:
        - ./client/public:/usr/client/public
        - ./client/app:/usr/client/app
        - ./client/package.json:/usr/client/package.json
        - ./client/.eslintrc.yml:/usr/client/.eslintrc.yml
        - ./client/brunch-config.js:/usr/client/brunch-config.js
    environment:
        - ALLOW_OVERRIDE=true
        - HOST_HOSTNAME=brunch-server
    command: brunch watch --server --port 80


proxy:
    image: haproxy:1.6
    links:
        - node-brunch
        - php-server
    ports:
      - "80:8080"

    volumes:
        - ./etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        - ./logs/haproxy:/var/log/haproxy
    environment:
        - ALLOW_OVERRIDE=true